### ISSUE TITLE
npm install 관련 오류 사항

### ISSUE THREAD

**Issue by joseph-106** [sinbox0701/campusmap-frontend#1]
`오류 내용`
20 vulnerabilities (18 moderate, 2 high)

dns-packet  <1.3.2 || >=2.0.0 <5.2.2
Severity: high
Memory Exposure - https://npmjs.com/advisories/1745
fix available via `npm audit fix`
node_modules/dns-packet

tar  <=3.2.2 || 4.0.0 - 4.4.14 || 5.0.0 - 5.0.6 || 6.0.0 - 6.1.1
Severity: high
Arbitrary File Creation/Overwrite due to insufficient absolute path sanitization - https://npmjs.com/advisories/1770
Arbitrary File Creation/Overwrite via insufficient symlink protection due to directory cache poisoning - https://npmjs.com/advisories/1771
fix available via `npm audit fix`
node_modules/tar

`npm audit fix` 입력 시
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: type-fest@0.8.1
npm ERR! node_modules/type-fest
npm ERR!   type-fest@"^0.8.1" from globals@12.4.0
npm ERR!   node_modules/@eslint/eslintrc/node_modules/globals
npm ERR!     globals@"^12.1.0" from @eslint/eslintrc@0.3.0
npm ERR!     node_modules/@eslint/eslintrc
npm ERR!       @eslint/eslintrc@"^0.3.0" from eslint@7.19.0
npm ERR!       node_modules/eslint
npm ERR!         peer eslint@"^5.0.0 || ^6.0.0 || ^7.0.0" from @typescript-eslint/eslint-plugin@4.14.2
npm ERR!         node_modules/@typescript-eslint/eslint-plugin
npm ERR!         14 more (@typescript-eslint/experimental-utils, ...)
npm ERR!   type-fest@"^0.8.1" from read-pkg-up@7.0.1
npm ERR!   node_modules/@jest/core/node_modules/read-pkg-up
npm ERR!     read-pkg-up@"^7.0.1" from jest-resolve@26.6.2
npm ERR!     node_modules/@jest/core/node_modules/jest-resolve
npm ERR!       jest-resolve@"^26.6.2" from @jest/core@26.6.3
npm ERR!       node_modules/@jest/core
npm ERR!         @jest/core@"^26.6.0" from jest@26.6.0
npm ERR!         node_modules/jest
npm ERR!         1 more (jest-cli)
npm ERR!   7 more (read-pkg-up, globals, read-pkg-up, read-pkg-up, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional type-fest@"^0.13.1" from @pmmmwh/react-refresh-webpack-plugin@0.4.3
npm ERR! node_modules/@pmmmwh/react-refresh-webpack-plugin
npm ERR!   @pmmmwh/react-refresh-webpack-plugin@"0.4.3" from react-scripts@4.0.2
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"4.0.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\sjjos\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sjjos\AppData\Local\npm-cache\_logs\2021-08-22T09_03_53_637Z-debug.log

**Comment by sinbox0701** [comment]
> `오류 내용`
> 20 vulnerabilities (18 moderate, 2 high)
> 
> dns-packet <1.3.2 || >=2.0.0 <5.2.2
> Severity: high
> Memory Exposure - https://npmjs.com/advisories/1745
> fix available via `npm audit fix`
> node_modules/dns-packet
> 
> tar <=3.2.2 || 4.0.0 - 4.4.14 || 5.0.0 - 5.0.6 || 6.0.0 - 6.1.1
> Severity: high
> Arbitrary File Creation/Overwrite due to insufficient absolute path sanitization - https://npmjs.com/advisories/1770
> Arbitrary File Creation/Overwrite via insufficient symlink protection due to directory cache poisoning - https://npmjs.com/advisories/1771
> fix available via `npm audit fix`
> node_modules/tar
> 
> `npm audit fix` 입력 시
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! Found: type-fest@0.8.1
> npm ERR! node_modules/type-fest
> npm ERR! type-fest@"^0.8.1" from globals@12.4.0
> npm ERR! node_modules/@eslint/eslintrc/node_modules/globals
> npm ERR! globals@"^12.1.0" from @eslint/eslintrc@0.3.0
> npm ERR! node_modules/@eslint/eslintrc
> npm ERR! @eslint/eslintrc@"^0.3.0" from eslint@7.19.0
> npm ERR! node_modules/eslint
> npm ERR! peer eslint@"^5.0.0 || ^6.0.0 || ^7.0.0" from @typescript-eslint/eslint-plugin@4.14.2
> npm ERR! node_modules/@typescript-eslint/eslint-plugin
> npm ERR! 14 more (@typescript-eslint/experimental-utils, ...)
> npm ERR! type-fest@"^0.8.1" from read-pkg-up@7.0.1
> npm ERR! node_modules/@jest/core/node_modules/read-pkg-up
> npm ERR! read-pkg-up@"^7.0.1" from jest-resolve@26.6.2
> npm ERR! node_modules/@jest/core/node_modules/jest-resolve
> npm ERR! jest-resolve@"^26.6.2" from @jest/core@26.6.3
> npm ERR! node_modules/@jest/core
> npm ERR! @jest/core@"^26.6.0" from jest@26.6.0
> npm ERR! node_modules/jest
> npm ERR! 1 more (jest-cli)
> npm ERR! 7 more (read-pkg-up, globals, read-pkg-up, read-pkg-up, ...)
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peerOptional type-fest@"^0.13.1" from @pmmmwh/react-refresh-webpack-plugin@0.4.3
> npm ERR! node_modules/@pmmmwh/react-refresh-webpack-plugin
> npm ERR! @pmmmwh/react-refresh-webpack-plugin@"0.4.3" from react-scripts@4.0.2
> npm ERR! node_modules/react-scripts
> npm ERR! react-scripts@"4.0.2" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR! See C:\Users\sjjos\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\sjjos\AppData\Local\npm-cache_logs\2021-08-22T09_03_53_637Z-debug.log


npm install 먼저 실행
